### ISSUE TITLE
TypeError: 'bool' object is not subscriptable

### ISSUE THREAD

**Issue by asifahmad7007** [DIAGNijmegen/neural-odes-segmentation#1]
Hi, thanks a lot for the code and work! I am trying to run the code on Google Colab; every thing was going well, this error popped up!

`TypeError                                 Traceback (most recent call last)
<ipython-input-25-065f1b00c1d3> in <module>()
      2 else: lr = 1e-4
      3 
----> 4 run(lr, 600 - len(losses))

1 frames
/content/neural-odes-segmentation/train_utils.py in plot_losses(inputs, outputs, losses, val_losses, title, nfe, net)
      6     # plot statistics
      7     if nfe is not None:
----> 8         nfe[0].append(net.odeblock_down1.odefunc.nfe)
      9         nfe[1].append(net.odeblock_down2.odefunc.nfe)
     10         nfe[2].append(net.odeblock_down3.odefunc.nfe)

TypeError: 'bool' object is not subscriptable`

Your help in this regard would be very appreciated!

**Comment by HansPinckaers** [comment]
Thanks for trying the code, seems like I forgot to the a last push of the recent fixes. Will do it tomorrow!

**Comment by asifahmad7007** [comment]
> Thanks for trying the code, seems like I forgot to the a last push of the recent fixes. Will do it tomorrow!

> Thanks for trying the code, seems like I forgot to the a last push of the recent fixes. Will do it tomorrow!

Will be waiting!

**Comment by HansPinckaers** [comment]
It should be fixed now! 

Try this notebook: https://colab.research.google.com/drive/1JPuZhHWTWIlAnwdarFDhYYrHSt4YXK0C#forceEdit=true&sandboxMode=true (Note: training is quite slow on Google Colab.)
