### ISSUE TITLE
 ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by asifahmad7007** [DIAGNijmegen/neural-odes-segmentation#3]
Sir, another issue arises at the last cell, probably last issue!

`ValueError                               Traceback (most recent call last)
<ipython-input-41-dd41d5adb3d5> in <module>()
     20 
     21     f1_img = F1score(result, gt)
---> 22     hausdorff_img = ObjectHausdorff(result, gt)
     23     dice_img = ObjectDice(result, gt)
     24 

2 frames
<__array_function__ internals> in argmin(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its` 

ValueError: attempt to get argmin of an empty sequence

Please fix it too! Thanks a lot!

**Comment by HansPinckaers** [comment]
Could you maybe post the full error / stack trace?

**Comment by asifahmad7007** [comment]
Sure!
This the code in the last cell:

`dice, hausdorff, f1, dice_full = 0, 0, 0, 0

if TEST_UNODE: folder = 'results_unode'
elif TEST_UNET: folder = 'results_unet'
elif TEST_RESNET: folder = 'results_resnet'
    
images = []
for index in np.arange(1, 81):
    if index < 61: images.append(f'testA_{index}_anno.bmp')
    else: images.append(f'testB_{index - 60}_anno.bmp')
        
for i, fname in tqdm_notebook(enumerate(images), total=80):
    gt = PIL.Image.open(f'Warwick QU Dataset (Released 2016_07_08)/' + fname)
    image = PIL.Image.open(f'Warwick QU Dataset (Released 2016_07_08)/' + fname.replace('_anno', ''))
    
    result, resized = inference_image(net, image, shouldpad=TEST_UNET)
    result = postprocess(result, gt)

    gt = skimage.measure.label(np.array(gt))
    
    f1_img = F1score(result, gt)
    hausdorff_img = ObjectHausdorff(result, gt)
    dice_img = ObjectDice(result, gt)
    
    f1 += f1_img
    hausdorff += hausdorff_img
    dice += dice_img

    if i == 59:        
        diceA = dice 
        hausdorffA = hausdorff 
        f1A = f1

    print(i, f1_img, hausdorff_img, dice_img)

diceB = dice - diceA
hausdorffB = hausdorff - hausdorffA
f1B = f1 - f1A

print('ObjectDice:', dice / 80, 'A', diceA / 60, 'B', diceB / 20)
print('Hausdorff:', hausdorff / 80, 'A', hausdorffA / 60, 'B', hausdorffB / 20)
print('F1:', f1 / 80, 'A', f1A / 60, 'B', f1B / 20)`

And this is the error:

`
4% 3/80 [00:47<23:54, 18.63s/it]
0 0.15384615384615383 224.01320643748454 0.49374686670827617
1 0 329.14081268707594 0.26286680977971855
2 0 268.02615862319647 0.3676988475547136
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-dd41d5adb3d5> in <module>()
     20 
     21     f1_img = F1score(result, gt)
---> 22     hausdorff_img = ObjectHausdorff(result, gt)
     23     dice_img = ObjectDice(result, gt)
     24 

2 frames
/content/neural-odes-segmentation/metrics.py in ObjectHausdorff(S, G)
     49                 tildeSi = (S == listLabelS[iLabelS])
     50                 tempDist[iLabelS] = Hausdorff(tildeGi, tildeSi)
---> 51             minIdx = np.argmin(tempDist)
     52             tildeSi = (S == listLabelS[minIdx])
     53         tildeOmegai = tildeGi.sum() / totalAreaG

<__array_function__ internals> in argmin(*args, **kwargs)

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in argmin(a, axis, out)
   1220 
   1221     """
-> 1222     return _wrapfunc(a, 'argmin', axis=axis, out=out)
   1223 
   1224 

/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

ValueError: attempt to get argmin of an empty sequence`

**Comment by asifahmad7007** [comment]
My bad, sir! I could not share the stack trace.

**Comment by HansPinckaers** [comment]
I think the code crashes because the network's prediction is empty, this probably happened because you trained the network only for a few epochs.

**Comment by asifahmad7007** [comment]
> I think the code crashes because the network's prediction is empty, this probably happened because you trained the network only for a few epochs.

Yes, sir! It looks so.

**Comment by asifahmad7007** [comment]
I tried for 20 epochs. The same issue arised, sir.
