### ISSUE TITLE
Why training is slow on Google Colab?

### ISSUE THREAD

**Issue by asifehmad** [DIAGNijmegen/neural-odes-segmentation#8]
Hello, sir! Hope you are doing great. I am training this on Google Colab and not been able to train it for 600 epoch, even not able for 200 epochs, tried many time. I have few questions:
Why is it that much slow on Colab? Is there any soluton?
What if I change the **maximum number of steps for ode solver** to less or higher number? Will this affect the training speed or results?

With this speed on Google Colab I am not going to achieve my results for 600 epochs or around it.
I need your kind suggestions in this regard.

I am looking forward for your kind response.
Thanks and Regards,
Asif Ahmad

**Comment by hanspinckaers** [comment]
Hi Asif,

The main problem is the slow GPU you get on Google Colab. You can try tweaking the tolerance of the solver, but it will always be quite slow. 

Kind regards,
Hans

**Comment by asifehmad** [comment]
> Hi Asif,
> 
> The main problem is the slow GPU you get on Google Colab. You can try tweaking the tolerance of the solver, but it will always be quite slow.
> 
> Kind regards,
> Hans

Thank you so much, Hans!
